wordpress_importer/management/commands/import_from_wordpress.py, wordpress_importer/migrations/0003_importdownloaderror.py, wordpress_importer/migrations/0004_merge.py, wordpress_importer/models.py, wordpress_importer/tests/test_import_command.py, wordpress_importer/tests/test_models.py
=> OCW-16 #time 2h 

core/models.py, core/static/css/_main.scss, core/static/js/opencanada.js, core/templates/core/homepage-feature.html
OCW-20 #changed FieldPanel from articles to number_of_rows and number_of_columns
=> OCW-130 #comment Change the camera icon to red when clicked

articles/models.py, articles/templates/articles/article_page.html, articles/templates/articles/in_depth_page.html, articles/templates/articles/includes/in_the_series.html, core/static/css/_main.scss, core/static/css/_mixins.scss
OCW-136 #comment changed inline display on series contributors and topics to prevent wrapping under label
OCW-136 #comment ajdust margins and borders on in depth and article pages
OCW-136 #comment change image display on in-the series
=> OCW-136 #comment added margins to series articles

core/models.py, newsletter/admin.py, newsletter/migrations/0001_initial.py, newsletter/migrations/0002_auto_20150723_1822.py, newsletter/migrations/0003_auto_20150723_1843.py, newsletter/migrations/0004_auto_20150723_1914.py, newsletter/migrations/0005_auto_20150723_1924.py, newsletter/migrations/0006_auto_20150723_1932.py, newsletter/migrations/0007_auto_20150723_1945.py, newsletter/migrations/0008_auto_20150723_1950.py, newsletter/models.py, newsletter/tests.py, opencanada/settings/base.py
OCW-143 #comment created events model
OCW-146 #comment created organzation model
OCW-144 #comment created readings model ad external link
OCW-145 #comment created link to articles on newsletter page
=> OCW-149 #comment created newsletter app and newsletter page model

newsletter/migrations/0009_auto_20150724_1551.py, newsletter/models.py
OCW-155 #comment Added help text for internal articles to indicate feature
OCW-155 #comment fixed label/field on event date
=> OCW-155 #comment Fixed events reference in newsletter page panels

articles/migrations/0031_auto_20150812_2002.py, articles/migrations/0032_auto_20150813_1359.py, articles/migrations/0033_articlepage_last_updated.py, articles/migrations/0034_auto_20150813_1728.py, articles/migrations/0035_auto_20150813_1802.py, articles/migrations/0036_merge.py, articles/models.py, articles/templates/articles/article_page.html, articles/templates/articles/chaptered_article_page.html, articles/templates/articles/includes/share_links.html, articles/templates/articles/series_page.html, core/static/css/_main.scss, core/static/css/_variables.scss, core/static/js/opencanada.js
OCW-192 #comment themed twitter and facebook count and set a left margin on share links so they don't runover content
=> OCW-192 #comment added twitter and facebook counts with 10 minute cache

core/static/css/_main.scss, core/static/css/_mixins.scss, core/templates/core/header.html, core/templates/core/home_page.html
OCW-230 #comment added sections to homepage for more consistent styling
OCW-230 #comment updated font sizes
OCW-230 #comment added headings for each section
=> OCW-230 #comment added more buttons to features section

articles/migrations/0043_auto_20150818_1833.py, articles/migrations/0044_articlelistpage_filter_for_visualizations.py, articles/models.py, core/migrations/0010_auto_20150818_1942.py, core/models.py, core/static/css/_main.scss, core/templates/core/home_page.html
OCW-232 #comment updated model to support multiple rows but only two columns
OCW-232 #comment updates ArticlePageList model to filter for visualizations if selected
=> OCW-232 #comment display graphics/visualizations on homepage

core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/js/opencanada.js, core/templates/core/header.html
OCW-262 #comment moved main menu to left side of header, still need to update internal pages
=> OCW-262 #comment updated look of search box as per mockup

articles/templates/articles/article_page.html, articles/templates/articles/chaptered_article_page.html, articles/templates/articles/includes/article_teaser.html, articles/templates/articles/series_page.html, articles/templates/articles/topic_page.html, core/static/css/_main.scss, people/templates/people/contributor_page.html
OCW-252 #comment make h2 uppercase and remove images on recent posts
=> OCW-252 #comment make page narrower to match article pages

articles/templates/articles/article_page.html, articles/templates/articles/includes/share_links.html, core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/css/_variables.scss, people/templates/people/contributor_list_page.html
OCW-281 #comment created a subheading mixin and updated reference to subheadings in main including related articles, in the series
=> OCW-281 #comment fixed relative url in share links

core/static/css/_main.scss, core/static/js/opencanada.js
=> fixed share icon alignment

manage.py, requirements/base.txt
Doing this separately since it isn't really tied to any ticket.
=> Add support for .env files.

core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/js/features.js
=> OCW-320 camera updates on mobile and desktop

articles/templates/articles/includes/article-contributors.html, articles/templates/articles/includes/series_teaser.html, core/static/css/_article.scss, core/static/css/_homepage.scss, core/templates/core/home_page.html, core/templates/core/includes/section-circle-descriptions.html
OCW-441 #removed contributor div that was preventing wrapping on small screen
=> OCW-441 #comments aligning dividers on rows with headings across site

articles/templates/articles/article_page.html, articles/templates/articles/series_page.html, core/static/css/_article.scss, core/static/css/_contributor.scss, core/static/css/_homepage.scss, core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/css/_variables.scss
changed body font line-height to 165%
changed underline on subheadings to grey
changed font weight on overlay featuer headers to 700 weight
changed line-height on contributor lists
=> OCW-532 #comment changed font size in footer to be all 14px

core/static/css/_article.scss, core/static/css/_bootstrap.scss, core/static/css/_contributor.scss, core/static/css/_features.scss, core/static/css/_homepage.scss, core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/css/_variables.scss, core/static/css/opencanada.scss, core/templates/base.html, core/templates/core/home_page.html
OCW-533 #comment add webfont block to base to all over ride of fonts on other themes
OCW-533 #comment added features css and moved reusable items from homepage to features
OCW-533 #comment started renaming variables to be element specific instead of colour specific
OCW-533 #comment started moving specific styles to reusable mixins
=> OCW-533 #comment comment out bootstrap includes that we don't use

articles/templates/articles/includes/article-contributors.html, core/static/css/_article.scss, core/static/css/_contributor.scss, core/static/css/_features.scss, core/static/css/_main.scss, core/static/css/_mixins.scss, core/static/css/_variables.scss
OCW-594 #comment Changed font size for article titles and mobile article titles
OCW-594 #comment Fixed line heights and spacing on contributors bio and headshot
OCW-594 #comment adjusted space around share links on mobile and space above/below main
=> OCW-594 #comment Updated h2 on homepage to be grey with red hover state

articles/templates/articles/article_list_page.html, articles/templates/articles/external_article_list_page.html, articles/templates/articles/includes/article-metadata.html, articles/templates/articles/includes/article_teaser.html, articles/templates/articles/includes/related_articles.html, core/static/css/_article.scss, themes/templates/themes/dark/articles/article_page.html, themes/templates/themes/dark/articles/series_page.html
OCW-631 #comment ensure contributors are being displayed on related articles
OCW-631 #comment added font weight to chapters in article story
OCw-631 #comment suppress images on article list pages
=> OCW-631 #comment suppress dropcap style in teaser

articles/templates/articles/includes/related_articles.html, themes/templates/themes/dark/articles/article_page.html
OCW-670 #comment fixed display of content on related articles
=> OCW-670 #comment fixed merge conflict on dark theme article page

articles/templates/articles/article_page.html, articles/templates/articles/blocks/chapter.html, articles/templates/articles/includes/advanced-content.html, articles/templates/articles/includes/series-metadata.html, articles/templates/articles/includes/story-content.html, core/static/css/_article.scss, themes/static/themes/dark/css/dark_variables.scss, themes/static/themes/light/css/light_variables.scss, themes/static/themes/lind/css/lind_variables.scss, themes/templates/themes/dark/articles/article_page.html, themes/templates/themes/dark/articles/series_page.html, themes/templates/themes/light/articles/article_page.html, themes/templates/themes/light/articles/series_page.html, themes/templates/themes/lind/articles/article_page.html, themes/templates/themes/lind/articles/series_page.html
OCW-678 #comment making templates for advanced content and story content and updating all series and article pages
OCW-678 #comment fixed hover states for contributors with missing variables
=> OCW-678 #comment updated chapters to support full bleed content

themes/templates/themes/twitterati/articles/article_page.html
Arbitrary hot-fix version number...
=> Merging Release 1.18.0.1

themes/static/themes/kurdistan/css/kurdistan_layout.scss, themes/static/themes/kurdistan/css/kurdistan_variables.scss, themes/static/themes/leftistForeignPolicy/css/leftist_foreign_policy_layout.scss, themes/templates/themes/kurdistan/articles/article-feature.html, themes/templates/themes/leftistForeignPolicy/articles/article-feature.html
Some tweaks to the Kurdistan theme, and the fix for Google's latest version of oauth2client library.
=> OCW-2 Merge

themes/models.py
Moved the 'pushing' of the theme to sub objects to the serve function so that other "Themeable" pages don't overwrite the settings for objects of the page actually being rendered.
Changed imports based on flake8 so that I could commit.
=> Fix theme templates when using related items

articles/management/commands/inittwitterati.py, images/models.py, themes/migrations/0001_squashed_0025_remove_theme_json_file.py
Most of these changes are more incidental, though the image model changes are required by Wagtail 1.8
http://docs.wagtail.io/en/v1.8/releases/1.8.html#unique-together-constraint-on-custom-image-rendition-models-needs-updating
=> OCW-49 Updates for Wagtail 1.8

articles/templatetags/article_tags.py, core/templates/core/home_page.html, themes/models.py, themes/templates/themes/exceptionalism/articles/includes/advanced_content.html
Made a while ago but not merged into master yet.
Tested with Python 2.7.
=> Changes to support Python 3 better.

core/templatetags/core_tags.py
Fix for https://sentry.io/the-centre-for-international-g/opencanada/issues/857214538
=> fix: Catch AttributeError on request object when previewing newsletters

core/templates/base.html, themes/templates/themes/lind/articles/article_page.html, themes/templates/themes/lind/articles/series_page.html
resolves CIGIHub/cigi-tickets#62
=> CIGI-62: Migrate OpenCanada Typekit fonts

core/static/css/_footer.scss, core/static/css/_header.scss, core/templates/core/footer.html, core/templates/core/header.html, requirements.txt, themes/static/themes/components/css/_transparency.scss
Also fixed the footer on small screens after a previous release changing it to a 2-column layout.
=> Remove hiatus banner and CIGI affiliation from footer
